=== SDMXISTATTOOLKIT/META-DATA.MANAGER/App_upgrade/ws/NSI_WS/App_Data/rules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:this="http://ec.europa.eu/eurostat/sri/authorisation/1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://ec.europa.eu/eurostat/sri/authorisation/1.0" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xsd:complexType name="ruleType">
        <xsd:annotation>
            <xsd:documentation>Rule</xsd:documentation>
        </xsd:annotation>
        <xsd:attribute name="id" type="xsd:NCName" />
    </xsd:complexType>
    <xsd:complexType name="permissionsType">
        <xsd:sequence>
            <xsd:element name="permission" type="this:ruleType" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="baseEndpointType" abstract="true">
        <xsd:annotation>
            <xsd:documentation>Base type for REST and SOAP</xsd:documentation>
        </xsd:annotation>
        <xsd:choice>
            <xsd:element name="and" type="this:permissionsType" maxOccurs="unbounded" />
            <xsd:element name="or" type="this:permissionsType" maxOccurs="unbounded" />
        </xsd:choice>
        <xsd:attribute name="path" type="xsd:string" />
        <xsd:attribute name="allowAnonymous" type="xsd:boolean" default="false" />
    </xsd:complexType>
    <xsd:complexType name="prefixNamespace">
        <xsd:attribute name="prefix" type="xsd:NCName" />
        <xsd:attribute name="namespace" type="xsd:anyURI" />
    </xsd:complexType>
    <xsd:complexType name="xpathType">
        <xsd:annotation>
            <xsd:documentation>XPath used against incoming SOAP requests</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="declare" type="this:prefixNamespace" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="script" type="xsd:string" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="restResourceType">
        <xsd:annotation>
            <xsd:documentation>Permission for REST resources. The path can contain templates/wildcards. The method should have the
                HTTP Method
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexContent>
            <xsd:extension base="this:baseEndpointType">
                <xsd:attribute name="method" type="xsd:NMTOKEN" default="GET" />
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
    <xsd:complexType name="soapEndpointType">
        <xsd:annotation>
            <xsd:documentation>Permissions for SOAP endpoint</xsd:documentation>
        </xsd:annotation>
        <xsd:complexContent>
            <xsd:extension base="this:baseEndpointType">
                <xsd:sequence>
                    <xsd:element name="xpath" minOccurs="0" type="this:xpathType" />
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
    <xsd:element name="rules">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="rest" type="this:restResourceType" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="soap" type="this:soapEndpointType" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== SDMXISTATTOOLKIT/META-DATA.MANAGER/Net_Core_60/NSI_WS/App_Data/nsiws.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:rules xmlns:r="http://ec.europa.eu/eurostat/sri/authorisation/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ec.europa.eu/eurostat/sri/authorisation/1.0 rules.xsd">
  <!-- REST & SOAP rules -->
  <!-- Order is signifigant -->
  <!-- REST get data -->
  <r:rest path="/rest(/[V,v]\d+)?/data/[^/]+(/.*)?" method="GET" allowAnonymous="true">
    <r:and>
        <r:permission id="CanReadData"/>
    </r:and>
  </r:rest>
  <!--swagger-->
  <r:rest path="/swagger/[^/]+(/.*)?" method="GET" allowAnonymous="true">
    <r:and>
        <r:permission id="CanReadData"/>
    </r:and>
  </r:rest>
  <!-- Experimental feature, POST key in body. key=..... -->
  <r:rest path="/rest(/[V,v]\d+)?/data/[^/]+/body/?(/.*)?" method="POST" allowAnonymous="true">
    <r:and>
        <r:permission id="CanReadData"/>
    </r:and>
  </r:rest>
  <r:rest path="/rest(/[V,v]\d+)?/availableconstraint/[^/]+/body/?(/.*)?" method="POST" allowAnonymous="true">
    <r:and>
        <r:permission id="CanReadData"/>
    </r:and>
  </r:rest>
  <r:rest path="/rest(/[V,v]\d+)?/availability/[^/]+/body/?(/.*)?" method="POST" allowAnonymous="true">
    <r:and>
      <r:permission id="CanReadData"/>
    </r:and>
  </r:rest>
  <!-- available constraints aka actual constraints aka cube-->
  <r:rest path="/rest(/[V,v]\d+)?/availableconstraint/[^/]+(/.*)?" method="GET" allowAnonymous="true">
    <r:and>
      <r:permission id="CanReadData"/>
    </r:and>
  </r:rest>
  <r:rest path="/rest(/[V,v]\d+)?/availability/[^/]+(/.*)?" method="GET" allowAnonymous="true">
    <r:and>
      <r:permission id="CanReadData"/>
    </r:and>
  </r:rest>
  <!-- REST get structural metadata -->
  <!-- Path uses regular expression, a subset common to both Java and .NET. Uri Templates -->
  <r:rest path="/rest(/[V,v]\d+)?/(datastructure|metadatastructure|categoryscheme|conceptscheme|codelist|hierarchicalcodelist|organisationscheme|agencyscheme|dataproviderscheme|dataconsumerscheme|organisationunitscheme|dataflow|metadataflow|reportingtaxonomy|provisionagreement|structureset|process|categorisation|contentconstraint|attachmentconstraint|structure|actualconstraint|allowedconstraint)(/.*)?" method="GET" allowAnonymous="true">
    <r:and>
        <r:permission id="CanReadStructuralMetadata" />
    </r:and>
  </r:rest>
  <r:rest path="/rest(/[V,v]\d+)?/data(/.*)?" method="POST" allowAnonymous="false">
    <r:and>
        <r:permission id="CanImportData"/>
    </r:and>
  </r:rest>
  <r:rest path="/rest(/[V,v]\d+)?/structure/?" method="POST" allowAnonymous="false">
    <r:and>
        <r:permission id="CanReadStructuralMetadata" />
        <r:permission id="CanImportStructures"/>
<!--        <r:permission id="CanUpdateStructuralMetadata"/> -->
    </r:and>
  </r:rest>
  <r:rest path="/rest(/[V,v]\d+)?/(datastructure|metadatastructure|categoryscheme|conceptscheme|codelist|hierarchicalcodelist|organisationscheme|agencyscheme|dataproviderscheme|dataconsumerscheme|organisationunitscheme|dataflow|metadataflow|reportingtaxonomy|provisionagreement|structureset|process|categorisation|contentconstraint|attachmentconstraint|structure|actualconstraint|allowedconstraint)(/.*)?" method="PUT" allowAnonymous="false">
    <r:and>
        <r:permission id="CanReadStructuralMetadata" />
        <r:permission id="CanImportStructures"/>
<!--        <r:permission id="CanUpdateStructuralMetadata"/> -->
    </r:and>
  </r:rest>
  <r:rest path="/rest(/[V,v]\d+)?/(datastructure|metadatastructure|categoryscheme|conceptscheme|codelist|hierarchicalcodelist|organisationscheme|agencyscheme|dataproviderscheme|dataconsumerscheme|organisationunitscheme|dataflow|metadataflow|reportingtaxonomy|provisionagreement|structureset|process|categorisation|contentconstraint|attachmentconstraint|structure|actualconstraint|allowedconstraint)(/.*)?" method="DELETE" allowAnonymous="false">
    <r:and>
        <r:permission id="CanReadStructuralMetadata" />
        <r:permission id="CanImportStructures"/>
        <r:permission id="CanDeleteStructuralMetadata"/>
    </r:and>
  </r:rest>
  <r:rest path="/login/token" method="POST" allowAnonymous="false">
    <r:and>
        <r:permission id="Any"/>
    </r:and>
  </r:rest>
  <!-- Frontpage and API-->
  <r:rest allowAnonymous="true" method="GET" path="^/css/\w+\.css$">
    <r:and>
      <r:permission id="Any"/>
    </r:and> 
  </r:rest>
  <r:rest allowAnonymous="true" method="GET" path="^/images/\w+\.\w+$">
    <r:and>
      <r:permission id="Any"/>
    </r:and> 
  </r:rest>
  <r:rest allowAnonymous="true" method="GET" path="^/favicon.ico$">
  <r:and>
    <r:permission id="Any"/>
  </r:and> 
  </r:rest>
  <r:rest allowAnonymous="true" method="GET" path="^/(index\.\w*html)?$">
    <r:and>
      <r:permission id="Any"/>
    </r:and> 
  </r:rest>
  <r:rest allowAnonymous="true" method="GET" path="^/sdmx(_estat|_org|v21)/(schemas/)?\w+\.(wsdl|xsd)$">
    <r:and>
      <r:permission id="Any"/>
    </r:and> 
  </r:rest>
  <!-- last slash needed for .NET-->
  <r:rest allowAnonymous="true" method="GET" path="^/rest/application.wadl/?$">
    <r:and>
      <r:permission id="Any"/>
    </r:and> 
  </r:rest>
  <!-- SDMX v2.1 SOAP GET data -->
  <r:soap path="/SdmxService" allowAnonymous="true">
    <r:and>
        <r:permission id="CanReadData"/>
    </r:and>
    <r:xpath>
        <r:declare prefix="web" namespace="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/webservices"/>
        <r:declare prefix="soap" namespace="http://schemas.xmlsoap.org/soap/envelope/"/>
        <r:script><![CDATA[
            boolean(
                /soap:Envelope/soap:Body/web:GetStructureSpecificData 
                | /soap:Envelope/soap:Body/web:GetGenericData
                | /soap:Envelope/soap:Body/web:GetStructureSpecificTimeSeriesData 
                | /soap:Envelope/soap:Body/web:GetGenericTimeSeriesData
                )
            ]]>      
        </r:script>
    </r:xpath>
  </r:soap>
   <!-- SDMX v2.1 SOAP GET structural metadata -->
  <r:soap path="/SdmxService" allowAnonymous="true">
    <r:and>
        <r:permission id="CanReadStructuralMetadata"/>
    </r:and>
    <r:xpath>
        <r:declare prefix="web" namespace="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/webservices"/>
        <r:declare prefix="soap" namespace="http://schemas.xmlsoap.org/soap/envelope/"/>
        <r:script><![CDATA[
            boolean(/soap:Envelope/soap:Body/*[starts-with(local-name(),'Get') and namespace-uri()="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/webservices"])
            ]]>      
        </r:script>
    </r:xpath>
  </r:soap>
 <!-- SDMX v2.1 RR SOAP GET data -->
  <r:soap path="/SdmxRegistryService" allowAnonymous="false">
    <r:and>
        <r:permission id="CanReadData"/>
    </r:and>
    <r:xpath>
        <r:declare prefix="web" namespace="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/webservices"/>
        <r:declare prefix="soap" namespace="http://schemas.xmlsoap.org/soap/envelope/"/>
        <r:script><![CDATA[
            boolean(
                /soap:Envelope/soap:Body/web:GetStructureSpecificData 
                | /soap:Envelope/soap:Body/web:GetGenericData
                | /soap:Envelope/soap:Body/web:GetStructureSpecificTimeSeriesData 
                | /soap:Envelope/soap:Body/web:GetGenericTimeSeriesData
                )
            ]]>      
        </r:script>
    </r:xpath>
  </r:soap>
   <!-- SDMX v2.1 SOAP RR GET structural metadata -->
  <r:soap path="/SdmxRegistryService" allowAnonymous="false">
    <r:and>
        <r:permission id="CanReadStructuralMetadata"/>
    </r:and>
    <r:xpath>
        <r:declare prefix="web" namespace="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/webservices"/>
        <r:declare prefix="soap" namespace="http://schemas.xmlsoap.org/soap/envelope/"/>
        <r:script><![CDATA[
            boolean(/soap:Envelope/soap:Body/*[starts-with(local-name(),'Get') and namespace-uri()="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/webservices"])
            ]]>      
        </r:script>
    </r:xpath>
  </r:soap>
   <!-- SDMX v2.1 SOAP RR Append structural metadata -->
   <!-- NOTE RR messages may contain multiple actions. This is not supported currently in NSI WS-->
  <r:soap path="/SdmxRegistryService" allowAnonymous="false">
    <r:and>
        <r:permission id="CanReadStructuralMetadata"/>
        <r:permission id="CanImportStructures"/>
    </r:and>
    <r:xpath>
        <r:declare prefix="web" namespace="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/webservices"/>
        <r:declare prefix="soap" namespace="http://schemas.xmlsoap.org/soap/envelope/"/>
        <r:declare prefix="m" namespace="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message"/>
        <r:script><![CDATA[
          boolean(
          /soap:Envelope/soap:Body/web:RegistryInterfaceRequest/m:RegistryInterface/m:SubmitStructureRequest[@action="Append"]
          | /soap:Envelope/soap:Body/web:SubmitStructure/m:SubmitStructureRequest/m:SubmitStructureRequest[@action="Append"]
          )
            ]]>
        </r:script>
    </r:xpath>
  </r:soap>
   <!-- SDMX v2.1 SOAP RR Update structural metadata -->
   <!-- NOTE RR messages may contain multiple actions. This is not supported currently in NSI WS-->
  <r:soap path="/SdmxRegistryService" allowAnonymous="false">
    <r:and>
        <r:permission id="CanReadStructuralMetadata"/>
        <r:permission id="CanImportStructures"/>
        <!--<r:permission id="CanUpdateStructuralMetadata"/>-->
    </r:and>
    <r:xpath>
        <r:declare prefix="web" namespace="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/webservices"/>
        <r:declare prefix="soap" namespace="http://schemas.xmlsoap.org/soap/envelope/"/>
        <r:declare prefix="m" namespace="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message"/>
        <r:script><![CDATA[
          boolean(
